### ISSUE TITLE
有概率出现的bug

### ISSUE THREAD

**Issue by lehhair** [halo-sigs/vscode-extension-halo#1]
![Code_D3a8FcyVwf](https://github.com/halo-sigs/vscode-extension-halo/assets/82690391/abd33f19-eda6-4919-9f64-7116f7c286d0)

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/vscode-extension-halo/commit/feeabd5f06c16b7ed84b3781a828e4f9f7b50eb4 中修复。

/close
