### ISSUE TITLE
一直卡在请选择一个附件存储策略

### ISSUE THREAD

**Issue by OxygenLost** [halo-sigs/vscode-extension-halo#11]
![image](https://github.com/halo-sigs/vscode-extension-halo/assets/89474311/67ed6745-3755-4da0-bd66-4ec7cf7fde59)

**Comment by ruibaby** [comment]
检查一下地址、用户名、密码是否有误。其中地址需要携带 `https://`。

**Comment by itwubin** [comment]
> 检查一下地址、用户名、密码是否有误。其中地址需要携带 `https://`。

请问地址配置哪个，有特定要求嘛，比如我的首页地址是：http://ip:8080（前台地址），也是一直卡在 请选择一个附件存储策略

**Comment by YBYCS** [comment]
同卡在这里

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/vscode-extension-halo/commit/c4988e352460e1c3e31b7c346dbb053b417dfb0f 中优化，现在支持校验地址是否设置正确。

/close
