### ISSUE TITLE
能否将publish项改成默认true？

### ISSUE THREAD

**Issue by luanshang** [halo-sigs/vscode-extension-halo#12]
每次publish都是false，我还需要将之改成true，再发布一遍，才能在我的博客中看到文章

**Comment by ruibaby** [comment]
目前这样做的目的是防止再写文章的过程中就直接发布了文章，防止你的访客看到不完整的文章。后续计划是增加一个选项，让使用者自行决定。

**Comment by ruibaby** [comment]
你现在可以自行在开头写元数据，比如：

```
halo:
  publish: true
```
