### ISSUE TITLE
别名问题

### ISSUE THREAD

**Issue by it985** [halo-sigs/vscode-extension-halo#13]
1
![06578864aea33a2a4b19755f6d578e8](https://github.com/halo-sigs/vscode-extension-halo/assets/62421120/aeda1026-e3ad-43d4-89ef-3b0ba41dacf4)
使用vs插件push文章后，文章url并没有走预设值
![image](https://github.com/halo-sigs/vscode-extension-halo/assets/62421120/61321313-c6a4-4651-b2ea-69ca33685c7f)
而是走的拼音
期望：走预设值
2 希望在 yaml 代码中添加更多信息，希望在 #3 之中，新增 别名，置顶，封图，发布时间，更新时间等 相关参数

**Comment by ruibaby** [comment]
目前已经在 https://github.com/halo-sigs/vscode-extension-halo/commit/745f0604769fe442c6ab135bc1eb5b3b1ad5ee01 中允许自定义 slug，但暂时还不能根据 Halo 的设置来自动生成 slug。其他关于封面图、摘要等已经在 https://github.com/halo-sigs/vscode-extension-halo/commit/30a58aaf3270b478ad0f0110b08d8fa311c9bee8 中支持。
