### ISSUE TITLE
成功推送的文章无法正确加载 html 内容

### ISSUE THREAD

**Issue by Mrered** [halo-sigs/vscode-extension-halo#2]
<img width="1544" alt="image" src="https://github.com/halo-sigs/vscode-extension-halo/assets/34948506/f93438e9-3783-40bd-9e95-683cb51e3c08">

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-sigs/vscode-extension-halo/commit/337514a64db4f2a60568af48fa9beafb4e92659c 中支持。

/close
