### ISSUE TITLE
Is this extension for halo2.x?

### ISSUE THREAD

**Issue by redquilt** [halo-sigs/vscode-extension-halo#5]
I wonder if this extension is for halo 2.x or halo 1.x, thank you for reply!

**Comment by JohnNiang** [comment]
Sure, the extension is only for Halo 2.x now.

**Comment by redquilt** [comment]
这个插件可以加批量上传markdown的功能吗？
另外，能告诉我你在哪里查到halo2.x的api吗，感谢

**Comment by ruibaby** [comment]
> 这个插件可以加批量上传markdown的功能吗？ 另外，能告诉我你在哪里查到halo2.x的api吗，感谢

批量发布的功能可以跟踪：https://github.com/halo-sigs/vscode-extension-halo/issues/10

API 文档目前可能需要手动在[本地启动开发环境](https://docs.halo.run/developer-guide/core/run)，然后访问 `/swagger-ui.html`。

/close
