### ISSUE TITLE
有详细的教程吗？

### ISSUE THREAD

**Issue by renshinizhenhao** [halo-sigs/vscode-extension-halo#6]
弄了一会，没有搞明白。
插件我安装了，怎么配置呢？

**Comment by ruibaby** [comment]
https://github.com/halo-sigs/vscode-extension-halo/blob/main/README-zh.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by renshinizhenhao** [comment]
> https://github.com/halo-sigs/vscode-extension-halo/blob/main/README-zh.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

它让我先创建个halo.json文件。这个文件在哪里创建？创建的时候输入什么内容？

**Comment by ruibaby** [comment]
> > [`main`/README-zh.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95](https://github.com/halo-sigs/vscode-extension-halo/blob/main/README-zh.md?rgh-link-date=2023-09-24T11%3A59%3A28Z#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
> 
> 它让我先创建个halo.json文件。这个文件在哪里创建？创建的时候输入什么内容？

这个提示应该是比较老版本的插件，不适用于 Halo 2，你应该需要更新 VSCode 版本最低到 1.79.0，然后会收到此插件的最新版本。

**Comment by renshinizhenhao** [comment]
> > > [`main`/README-zh.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95](https://github.com/halo-sigs/vscode-extension-halo/blob/main/README-zh.md?rgh-link-date=2023-09-24T11%3A59%3A28Z#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
> > 
> > 
> > 它让我先创建个halo.json文件。这个文件在哪里创建？创建的时候输入什么内容？
> 
> 这个提示应该是比较老版本的插件，不适用于 Halo 2，你应该需要更新 VSCode 版本最低到 1.79.0，然后会收到此插件的最新版本。

我升级了 Visual Studio Code 按照文中的操作弄好了。这个确实很棒！！！谢谢大佬！！！
